spring.application.name=Tutorials
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.show-sql=true

app.jwt.secret=mysecretd1dfbe5eddab2f870317c88ddad10a72
app.jwt.expiration=7200000
